### ISSUE TITLE
Add php version check during installation

### ISSUE THREAD

**Issue by Ruslan-Aleev** [BobRay/UpgradeMODX#84]
It's not nice to see that a manager crashes with an error, and it can't be fixed quickly.

![php](https://github.com/BobRay/UpgradeMODX/assets/12523676/84d500f7-469b-4102-a175-81fbbcd3222e)

And in general, it is doubtful to require a PHP version from a small component; PHP 8 is not yet relevant for all sites.

**Comment by SnowCreative** [comment]
Yes, just discovered that, too. The error shows up at the top of the widget, and trying to upgrade generates a popup javascript error, like:

Error requesting page /assets/components/upgrademodx/connector.php?action=downloadfiles&props%5Bugm_setup_url%5D=https%3A%2F%2F[domainname] (etc.)

**Comment by BobRay** [comment]
Could you guys  be a little more specific. UGM itself does not require PHP 8.  Is this an issue with Guzzle (which I was forced to upgrade due to a security issue)?

**Comment by Ruslan-Aleev** [comment]
@BobRay 

> Could you guys be a little more specifi

The sequence of my actions.
1) We have a website on MODX 2.8.5, running on php version 7.4.
2) Using the package manager, I update UpgradeMODX to version 2.3.4-pl.
3) And that’s it, I go to the manager, but it doesn’t work with the error above.

As I understand it, the php version is checked in the file - `/core/components/upgrademodx/vendor/composer/platform_check.php`

**Comment by Ruslan-Aleev** [comment]
Thanks for the answer.
Alternatively, you can specify php requirements in the installer that would block the installation of a new version of the component, and the user would decide for himself whether to change the php version or not; If the problem cannot be fixed.

**Comment by BobRay** [comment]
The problem is mostly solved, except for some spurious error messages in the console when you install or upgrade.

As a workaround, you can put this in the composer.json file:

"config": {
        "platform-check": false
    },

If there is already a config section, just add the middle line to it. I think that will makes things work, but I haven't tested it.

**Comment by BobRay** [comment]
The repo containing the new UGM code with Guzzle7 is [here" ](https://github.com/BobRay/UpgradeMODX/tree/temp)

**Comment by BobRay** [comment]
Fixed in 2.3.9-pl -- released.
Closing

**Comment by SnowCreative** [comment]
Works great, Bob. Thanks for the quick turnaround!

**Comment by Ruslan-Aleev** [comment]
**No, the problem persists :(**

On php 8.2 we have this error:
![error_82](https://github.com/user-attachments/assets/38532de2-e579-43fa-8b5e-3159cdf31b98)

On 7.2 we have this:
![error_72](https://github.com/user-attachments/assets/3b107c79-df6e-4dc6-8f94-f2458e75101c)

**As a result, the site cannot be used.**

p.s. Does such a simple component really require such crooked dependencies?.. It's strange and sad...

**Comment by BobRay** [comment]
The deprecation issue appears to be a problem in xPDO, so I can't fix it.

It appears that Guzzle 7 itself [does not require PHP 8](https://docs.guzzlephp.org/en/stable/overview.html#:~:text=Guzzle%20utilizes%20PSR%2D1%2C%20PSR,version%20requirement%20of%20PHP%207.2.). Nor does the MODX Guzzle7 extra as far as I can tell. In current UGM version, the `composer.json` file has only this:

```
"config": {
        "platform": {
            "php": "7.2.5"
        }
    },
```

If your `composer.json` file still has the `platform-check` line, set it to false and remove the platfform_check.php file.

**Comment by Ruslan-Aleev** [comment]
Thanks for the information!
